import os
import argparse
import subprocess
import sys

def run_command(command, description):
    print(f"\n{'='*60}")
    print(f"Executing: {description}")
    print(f"{'='*60}")
    
    try:
        # Run the command and stream output to terminal
        result = subprocess.run(
            command,
            check=True,
            text=True,
            shell=True
        )
    except subprocess.CalledProcessError as e:
        print(f"\n[ERROR] Command failed with exit code {e.returncode}: {command}")
        sys.exit(1)

def main():
    parser = argparse.ArgumentParser(description="Run the complete Clara AI Pipeline (Demo -> Onboarding)")
    parser.add_argument("--demo_json", required=True, help="Path to input json (demo transcript)")
    parser.add_argument("--onboarding_text", required=True, help="Path to onboarding chat/transcript text file")
    parser.add_argument("--account_id", help="Account ID for storage. Auto-generated if omitted.")
    args = parser.parse_args()

    # 1. Run Pipeline A (Demo)
    cmd_a = f"{sys.executable} scripts/pipeline_a_demo.py --input \"{args.demo_json}\""
    if args.account_id:
        cmd_a += f" --account_id \"{args.account_id}\""
        
    run_command(cmd_a, "Pipeline A (Demo Phase)")

    # 2. Determine the Account ID generated by Pipeline A
    # If it wasn't provided, it auto-generated. We need to find the newest one.
    if args.account_id:
        final_account_id = args.account_id
    else:
        base_dir = "outputs/accounts"
        existing = [d for d in os.listdir(base_dir) if d.startswith("account-")]
        if not existing:
            print("[ERROR] Could not locate the auto-generated account ID.")
            sys.exit(1)
            
        nums = []
        for d in existing:
            try:
                nums.append(int(d.split("-")[1]))
            except ValueError:
                pass
        latest_num = max(nums)
        final_account_id = f"account-{latest_num}"

    print(f"\n[INFO] Proceeding with Account ID: {final_account_id}")

    # 3. Run Pipeline B (Onboarding)
    cmd_b = f"{sys.executable} scripts/pipeline_b_onboarding.py --account_id \"{final_account_id}\" --input \"{args.onboarding_text}\""
    run_command(cmd_b, "Pipeline B (Onboarding Phase)")

    print(f"\n{'='*60}")
    print(f"MASTER PIPELINE COMPLETE")
    print(f"Files saved to outputs/accounts/{final_account_id}/")
    print(f"{'='*60}\n")

if __name__ == "__main__":
    main()
